### ISSUE TITLE
IFP_generation_dissociation_trajectories

### ISSUE THREAD

**Issue by AmyOo312** [HITS-MCM/MD-IFP#12]
Hello,

I was trying to generate IFP for my dissociation trajectories and I am facing this error. If you have any ideas how I could fix this problem, please let me know.

Thank you.

total number of frames= 526; file size 823 M
>>>sub-system selected   protein or (resname HOH WAT SOL)  or (resname  9JU302)
Warning: Failed to read this trajectory

ERROR: IFP either were not generated or could not be stored in the traj object!

>>>>>>>>>= 19 F10_001_40_40_p//RAMD\9.dcd
total number of frames= 607; file size 950 M
>>>sub-system selected   protein or (resname HOH WAT SOL)  or (resname  9JU302)
Warning: Failed to read this trajectory

ERROR: IFP either were not generated or could not be stored in the traj object!

++++Will be saved +++++ ['RAMD']
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
ERROR: failed to save properties for the replica  RAMD  since the trajectiry was not analyzed
Traceback (most recent call last):
  File "D:\XX\XX\ifp_generation.py", line 43, in <module>
    tr.ramd.IFP_save(tr.PRJ_DIR+name+"_RAMD_com.pkl")
  File "D:\XX\XX\Scripts\Trajectories.py", line 584, in IFP_save
    df1.to_pickle(file)
AttributeError: 'NoneType' object has no attribute 'to_pickle'

**Comment by haoxuanluo731** [comment]
I also find this problem，I want to know whether you have solve it
